In [2]:
import numpy as np
import pandas as pd
pd.set_option("display.precision", 2)

Let's read some data

In [3]:
df = pd.read_csv("https://raw.githubusercontent.com/Yorko/mlcourse.ai/master/data/telecom_churn.csv")
df.head()

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False
1,OH,107,415,No,Yes,26,161.6,123,27.47,195.5,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False
2,NJ,137,415,No,No,0,243.4,114,41.38,121.2,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False
3,OH,84,408,Yes,No,0,299.4,71,50.90,61.9,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False
4,OK,75,415,Yes,No,0,166.7,113,28.34,148.3,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False

Explore dataset:

* shape with `.shape`
* columns with `.columns`
* info with `.info()`

In [4]:
df.shape

(3333, 20)

In [5]:
df.columns

Index(['State', 'Account length', 'Area code', 'International plan',
       'Voice mail plan', 'Number vmail messages', 'Total day minutes',
       'Total day calls', 'Total day charge', 'Total eve minutes',
       'Total eve calls', 'Total eve charge', 'Total night minutes',
       'Total night calls', 'Total night charge', 'Total intl minutes',
       'Total intl calls', 'Total intl charge', 'Customer service calls',
       'Churn'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3333 entries, 0 to 3332
Data columns (total 20 columns):
State                     3333 non-null object
Account length            3333 non-null int64
Area code                 3333 non-null int64
International plan        3333 non-null object
Voice mail plan           3333 non-null object
Number vmail messages     3333 non-null int64
Total day minutes         3333 non-null float64
Total day calls           3333 non-null int64
Total day charge          3333 non-null float64
Total eve minutes         3333 non-null float64
Total eve calls           3333 non-null int64
Total eve charge          3333 non-null float64
Total night minutes       3333 non-null float64
Total night calls         3333 non-null int64
Total night charge        3333 non-null float64
Total intl minutes        3333 non-null float64
Total intl calls          3333 non-null int64
Total intl charge         3333 non-null float64
Customer service calls    3333 non-null int64
Churn                     3333 non-null bool
dtypes: bool(1), float64(8), int64(8), object(3)
memory usage: 498.1+ KB

## Change column from one type to another with `.astype("type")` method

For instance `df["col"] = df["col"].astype("int64")`

In [8]:
# let's change the target metric `churn` from bool to int64
df.Churn = df["Churn"].astype("int64")
df.head()

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.70,1,0
1,OH,107,415,No,Yes,26,161.6,123,27.47,195.5,103,16.62,254.4,103,11.45,13.7,3,3.70,1,0
2,NJ,137,415,No,No,0,243.4,114,41.38,121.2,110,10.30,162.6,104,7.32,12.2,5,3.29,0,0
3,OH,84,408,Yes,No,0,299.4,71,50.90,61.9,88,5.26,196.9,89,8.86,6.6,7,1.78,2,0
4,OK,75,415,Yes,No,0,166.7,113,28.34,148.3,122,12.61,186.9,121,8.41,10.1,3,2.73,3,0

Get statistical information with `.describe()` method

In [9]:
df.describe()

,Account length,Area code,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
count,3333.00,3333.00,3333.00,3333.00,3333.00,3333.00,3333.00,3333.00,3333.00,3333.00,3333.00,3333.00,3333.00,3333.00,3333.00,3333.00,3333.00
mean,101.06,437.18,8.10,179.78,100.44,30.56,200.98,100.11,17.08,200.87,100.11,9.04,10.24,4.48,2.76,1.56,0.14
std,39.82,42.37,13.69,54.47,20.07,9.26,50.71,19.92,4.31,50.57,19.57,2.28,2.79,2.46,0.75,1.32,0.35
min,1.00,408.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,23.20,33.00,1.04,0.00,0.00,0.00,0.00,0.00
25%,74.00,408.00,0.00,143.70,87.00,24.43,166.60,87.00,14.16,167.00,87.00,7.52,8.50,3.00,2.30,1.00,0.00
50%,101.00,415.00,0.00,179.40,101.00,30.50,201.40,100.00,17.12,201.20,100.00,9.05,10.30,4.00,2.78,1.00,0.00
75%,127.00,510.00,20.00,216.40,114.00,36.79,235.30,114.00,20.00,235.30,113.00,10.59,12.10,6.00,3.27,2.00,0.00
max,243.00,510.00,51.00,350.80,165.00,59.64,363.70,170.00,30.91,395.00,175.00,17.77,20.00,20.00,5.40,9.00,1.00

By default `.describe()` shows information only on numerical features, 
to include info on non-numeric as well pass type of elements 
you would like to get stats for - `describe(include = ["object", "bool"])

In [11]:
df.describe(include = ["bool", "object"])

       State International plan Voice mail plan
count   3333               3333            3333
unique    51                  2               2
top       WV                 No              No
freq     106               3010            2411

For categorical features (type `object`) and boolean (type `bool`) we can use method
`value_counts()` to get counts.

In [13]:
df["Churn"].value_counts()

0    2850
1     483
Name: Churn, dtype: int64

By passing `normalize = True` to `value_counts()` we can get not counts but proportions

In [14]:
df.Churn.value_counts(normalize = True)

0    0.86
1    0.14
Name: Churn, dtype: float64

# Sorting

Done by `sort_values` on pandas object with parameters: 

* `by` - column to sort
* `ascending = False` - if we want to sort in decending order

In [16]:
df.sort_values(by = "Total day charge", ascending=False).head()

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
365,CO,154,415,No,No,0,350.8,75,59.64,216.5,94,18.40,253.9,100,11.43,10.1,9,2.73,1,1
985,NY,64,415,Yes,No,0,346.8,55,58.96,249.5,79,21.21,275.4,102,12.39,13.3,9,3.59,1,1
2594,OH,115,510,Yes,No,0,345.3,81,58.70,203.4,106,17.29,217.5,107,9.79,11.8,8,3.19,1,1
156,OH,83,415,No,No,0,337.4,120,57.36,227.4,116,19.33,153.9,114,6.93,15.8,7,4.27,0,1
605,MO,112,415,No,No,0,335.5,77,57.04,212.5,109,18.06,265.0,132,11.93,12.7,8,3.43,2,1

Sort by multiple columns by passing list to `by` and `asceding`

In [17]:
df.sort_values(by = ["Churn", "Total day charge"], 
              ascending=[True, False]).head()

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
688,MN,13,510,No,Yes,21,315.6,105,53.65,208.9,71,17.76,260.1,123,11.70,12.1,3,3.27,3,0
2259,NC,210,415,No,Yes,31,313.8,87,53.35,147.7,103,12.55,192.7,97,8.67,10.1,7,2.73,3,0
534,LA,67,510,No,No,0,310.4,97,52.77,66.5,123,5.65,246.5,99,11.09,9.2,10,2.48,4,0
575,SD,114,415,No,Yes,36,309.9,90,52.68,200.3,89,17.03,183.5,105,8.26,14.2,2,3.83,1,0
2858,AL,141,510,No,Yes,28,308.0,123,52.36,247.8,128,21.06,152.9,103,6.88,7.4,3,2.00,1,0

# Indexing and retrieving data

1. By specifing column name in squre bracets (i.e., `df["Colname"]`)
2. By specifing column name after dot (i.e., `df.Colname`)

In [22]:
print(round(df["Churn"].mean(), 2))
print(df.Churn.median())

0.14
0.0

## Boolean indexing
`df[P(df["Colname"])]`, where `P` - some logical condition (i.e., equality)

In [24]:
# Calculate average values for all columns for churned users
df[df.Churn == 1].mean()

Account length            102.66
Area code                 437.82
Number vmail messages       5.12
Total day minutes         206.91
Total day calls           101.34
Total day charge           35.18
Total eve minutes         212.41
Total eve calls           100.56
Total eve charge           18.05
Total night minutes       205.23
Total night calls         100.40
Total night charge          9.24
Total intl minutes         10.70
Total intl calls            4.16
Total intl charge           2.89
Customer service calls      2.23
Churn                       1.00
dtype: float64

In [25]:
# Select a single column after indexing
df[df.Churn == 0]['Total day minutes'].mean()

175.17575438596492

In [26]:
# Can combine conditions
df[(df.Churn == 0) & (df["International plan"] == "No")]["Total intl minutes"].max()

18.9

DataFrames can be indexed by serial number of row with: 

* `.loc[]` - indexing by name
* `.iloc[]` - indexing by number

In [27]:
# select first 6 rows and some columns
df.loc[0:5, "State":"Area code"]

  State  Account length  Area code
0    KS             128        415
1    OH             107        415
2    NJ             137        415
3    OH              84        408
4    OK              75        415
5    AL             118        510

In [28]:
df.iloc[12:18, 4:6]

   Voice mail plan  Number vmail messages
12              No                      0
13              No                      0
14              No                      0
15              No                      0
16             Yes                     27
17              No                      0

To get the first line of df we use `df[:1]`, last - `df[-1:]`

In [29]:
df[:1]

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.7,1,0

In [31]:
df[-1:]

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
3332,TN,74,415,No,Yes,25,234.4,113,39.85,265.9,82,22.6,241.4,77,10.86,13.7,4,3.7,0,0

# Applying functions to cells, columns and rows with `.apply()`

In [32]:
# find max of each numeric column
df.apply(np.max)

State                          WY
Account length                243
Area code                     510
International plan            Yes
Voice mail plan               Yes
Number vmail messages          51
Total day minutes         3.5e+02
Total day calls               165
Total day charge               60
Total eve minutes         3.6e+02
Total eve calls               170
Total eve charge               31
Total night minutes         4e+02
Total night calls             175
Total night charge             18
Total intl minutes             20
Total intl calls               20
Total intl charge             5.4
Customer service calls          9
Churn                           1
dtype: object

By default `.apply()` works on rows, to apply to column pass `(axis = 1)` as an argument

In [37]:
# Works with lambdas

# find information on all states which starts with 'W'
df[df.State.apply(lambda state: state[0] == "W")].head(15)

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
9,WV,141,415,Yes,Yes,37,258.6,84,43.96,222.0,111,18.87,326.4,97,14.69,11.2,5,3.02,0,0
26,WY,57,408,No,Yes,39,213.0,115,36.21,191.1,112,16.24,182.7,115,8.22,9.5,3,2.57,0,0
44,WI,64,510,No,No,0,154.0,67,26.18,225.8,118,19.19,265.3,86,11.94,3.5,3,0.95,1,0
49,WY,97,415,No,Yes,24,133.2,135,22.64,217.2,58,18.46,70.6,79,3.18,11.0,3,2.97,1,0
54,WY,87,415,No,No,0,151.0,83,25.67,219.7,116,18.67,203.9,127,9.18,9.7,3,2.62,5,1
58,WI,68,415,No,No,0,148.8,70,25.30,246.5,164,20.95,129.8,103,5.84,12.1,3,3.27,3,0
65,WA,40,415,No,Yes,41,148.1,74,25.18,169.5,88,14.41,214.1,102,9.63,6.2,5,1.67,2,0
66,WY,43,415,Yes,No,0,251.5,105,42.76,212.8,104,18.09,157.8,67,7.10,9.3,4,2.51,0,0
80,WV,144,415,No,No,0,201.1,99,34.19,303.5,74,25.80,224.0,119,10.08,13.2,2,3.56,1,0
87,WV,111,510,No,No,0,214.3,118,36.43,208.5,76,17.72,182.4,98,8.21,12.0,2,3.24,1,0
146,WA,127,408,No,No,0,146.7,91,24.94,203.5,78,17.30,203.4,110,9.15,13.7,3,3.70,1,0
180,WV,94,510,Yes,Yes,23,197.1,125,33.51,214.5,136,18.23,282.2,103,12.70,9.5,5,2.57,4,0
188,WY,164,510,No,No,0,160.6,111,27.30,163.2,126,13.87,187.1,112,8.42,9.0,3,2.43,1,0
189,WA,51,408,No,No,0,232.4,109,39.51,187.4,95,15.93,231.2,107,10.40,9.1,3,2.46,1,0
204,WA,157,415,No,No,0,152.7,105,25.96,257.5,80,21.89,198.1,93,8.91,9.4,4,2.54,1,0

## Replace values in a column with `.map()` which requires a dictionary for replacement

In [38]:
# create dictionary
d = {"No": False, 
    "Yes" : True}

df["International plan"] = df["International plan"].map(d)
df.head()

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,False,Yes,25,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.70,1,0
1,OH,107,415,False,Yes,26,161.6,123,27.47,195.5,103,16.62,254.4,103,11.45,13.7,3,3.70,1,0
2,NJ,137,415,False,No,0,243.4,114,41.38,121.2,110,10.30,162.6,104,7.32,12.2,5,3.29,0,0
3,OH,84,408,True,No,0,299.4,71,50.90,61.9,88,5.26,196.9,89,8.86,6.6,7,1.78,2,0
4,OK,75,415,True,No,0,166.7,113,28.34,148.3,122,12.61,186.9,121,8.41,10.1,3,2.73,3,0

## Replace with `.replace() method

requires a dictionary with two elements: 
    
* Column to replace value in 
* Dictionary with replacement values

In [39]:
df = df.replace({"Voice mail plan": d})
df.head()

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,False,True,25,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.70,1,0
1,OH,107,415,False,True,26,161.6,123,27.47,195.5,103,16.62,254.4,103,11.45,13.7,3,3.70,1,0
2,NJ,137,415,False,False,0,243.4,114,41.38,121.2,110,10.30,162.6,104,7.32,12.2,5,3.29,0,0
3,OH,84,408,True,False,0,299.4,71,50.90,61.9,88,5.26,196.9,89,8.86,6.6,7,1.78,2,0
4,OK,75,415,True,False,0,166.7,113,28.34,148.3,122,12.61,186.9,121,8.41,10.1,3,2.73,3,0

# Grouping

`df.groupby(by = [grouping_columns])[columns_subset].function()`

In [41]:
df.groupby(["Churn"])[["Total day minutes", "Total day calls"]].describe(percentiles = [])

      Total day minutes                                   Total day calls  \
                  count    mean    std  min    50%    max           count
Churn
0                2850.0  175.18  50.18  0.0  177.2  315.6          2850.0
1                 483.0  206.91  69.00  0.0  217.6  350.8           483.0


         mean    std  min    50%    max
Churn
0      100.28  19.80  0.0  100.0  163.0
1      101.34  21.58  0.0  103.0  165.0

By using `.agg([function1, function2, ...])` we can get different stats

In [45]:
df.groupby(["Churn"])[["Total day minutes", "Total day calls"]]\
.agg([np.mean, np.std, np.min, np.max])

      Total day minutes                    Total day calls
                   mean    std amin   amax            mean    std amin amax
Churn
0                175.18  50.18  0.0  315.6          100.28  19.80    0  163
1                206.91  69.00  0.0  350.8          101.34  21.58    0  165

# Summary tables with `pd.crosstab()`
pass object inside parentheses

In [46]:
pd.crosstab(df.Churn, df["International plan"])

International plan  False  True
Churn
0                    2664    186
1                     346    137

Use `.normalize=True` to get proportions

In [47]:
pd.crosstab(df.Churn, df["International plan"], normalize = True)

International plan  False  True
Churn
0                     0.8   0.06
1                     0.1   0.04

# Pivot tables with `.pivot_table()`

`.pivot_table([column1, column2, ...], [rows], aggfunc = "function")`

In [49]:
df.pivot_table(["Total day calls", "Total eve calls", "Total night calls"], 
               ["Area code"], aggfunc = "mean", margins = True)

           Total day calls  Total eve calls  Total night calls
Area code
408                 100.50            99.79              99.04
415                 100.58           100.50             100.40
510                 100.10            99.67             100.60
All                 100.44           100.11             100.11

# DataFrame transformations

In [53]:
# add total calls column
total_calls = df["Total day calls"] + df['Total night calls'] + \
df["Total eve calls"] + df['Total intl calls']
df["Total calls"] = total_calls

In [54]:
df.columns

Index(['State', 'Account length', 'Area code', 'International plan',
       'Voice mail plan', 'Number vmail messages', 'Total day minutes',
       'Total day calls', 'Total day charge', 'Total eve minutes',
       'Total eve calls', 'Total eve charge', 'Total night minutes',
       'Total night calls', 'Total night charge', 'Total intl minutes',
       'Total intl calls', 'Total intl charge', 'Customer service calls',
       'Churn', 'Total calls'],
      dtype='object')

## Delete column with `.drop([cols])`

Requires to specify axis: *1* for columns and *0* for rows (default). 

Also there's an `inplace` argument - if `True`, the current dataframe is changed, otherwise the new one is created

In [55]:
df.drop(["Total calls"], axis = 1, inplace=True)

We can delete rows as well

In [56]:
df.drop([1, 2]).head()

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,False,True,25,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.70,1,0
3,OH,84,408,True,False,0,299.4,71,50.90,61.9,88,5.26,196.9,89,8.86,6.6,7,1.78,2,0
4,OK,75,415,True,False,0,166.7,113,28.34,148.3,122,12.61,186.9,121,8.41,10.1,3,2.73,3,0
5,AL,118,510,True,False,0,223.4,98,37.98,220.6,101,18.75,203.9,118,9.18,6.3,6,1.70,0,0
6,MA,121,510,False,True,24,218.2,88,37.09,348.5,108,29.62,212.6,118,9.57,7.5,7,2.03,3,0

# 2. Work on predicting telecom churn

In [58]:
# explore data
pd.crosstab(df["Churn"], df["International plan"], margins = True, normalize=True)

International plan  False  True   All
Churn
0                     0.8  0.06  0.86
1                     0.1  0.04  0.14
All                   0.9  0.10  1.00

In [61]:
# Visualize
import matplotlib.pyplot as plt
import seaborn as sns
%config InlineBackend.figure_format = "svg"

In [63]:
sns.countplot(x = "International plan", hue = "Churn", data = df)

In [66]:
pd.crosstab(df.Churn, df["Customer service calls"], margins = True)

Customer service calls    0     1    2    3    4   5   6  7  8  9   All
Churn
0                       605  1059  672  385   90  26   8  4  1  0  2850
1                        92   122   87   44   76  40  14  5  1  2   483
All                     697  1181  759  429  166  66  22  9  2  2  3333

In [67]:
sns.countplot(data = df, x = "Customer service calls", hue = "Churn")

In [68]:
# let's add a binary feature `Customer service calls > 3` and compare it to churn
df["Many_service_calls"] = (df["Customer service calls"] > 3).astype("int")
pd.crosstab(df.Many_service_calls, df.Churn, margins = True)

Churn                  0    1   All
Many_service_calls
0                   2721  345  3066
1                    129  138   267
All                 2850  483  3333

In [69]:
sns.countplot(data = df, 
             x = "Many_service_calls", 
             hue = "Churn")

In [70]:
# we can build cross tab with combination of columns
pd.crosstab(df.Many_service_calls & df["International plan"], 
           df.Churn)

Churn     0    1
row_0
False  2841  464
True      9   19

We can calculate accuracy of our prediction by summing values off main diagonal:
    
* **464** - we expected customer not to churn by they churned
* **9** - we expected them to churn but they did not

which gives us `(464 + 9)/3333 = 85.8%` accuracy